export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: 'admin' | 'practitioner' | 'staff';
          practice_name: string | null;
          credentials: string | null;
          registration_number: string | null;
          phone: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: 'admin' | 'practitioner' | 'staff';
          practice_name?: string | null;
          credentials?: string | null;
          registration_number?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: 'admin' | 'practitioner' | 'staff';
          practice_name?: string | null;
          credentials?: string | null;
          registration_number?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      practice_settings: {
        Row: {
          id: string;
          user_id: string;
          practice_name: string;
          doctor_name: string;
          credentials: string | null;
          address: string;
          city: string;
          state: string;
          pincode: string;
          phone: string;
          email: string;
          registration_number: string | null;
          receipt_prefix: string;
          receipt_starting_number: number;
          date_format: string;
          currency_format: string;
          tax_enabled: boolean;
          tax_percentage: number;
          primary_language: string;
          secondary_language: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          practice_name: string;
          doctor_name: string;
          credentials?: string | null;
          address: string;
          city: string;
          state: string;
          pincode: string;
          phone: string;
          email: string;
          registration_number?: string | null;
          receipt_prefix?: string;
          receipt_starting_number?: number;
          date_format?: string;
          currency_format?: string;
          tax_enabled?: boolean;
          tax_percentage?: number;
          primary_language?: string;
          secondary_language?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          practice_name?: string;
          doctor_name?: string;
          credentials?: string | null;
          address?: string;
          city?: string;
          state?: string;
          pincode?: string;
          phone?: string;
          email?: string;
          registration_number?: string | null;
          receipt_prefix?: string;
          receipt_starting_number?: number;
          date_format?: string;
          currency_format?: string;
          tax_enabled?: boolean;
          tax_percentage?: number;
          primary_language?: string;
          secondary_language?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          age: number | null;
          gender: string | null;
          phone: string;
          email: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          pincode: string | null;
          medical_history: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          age?: number | null;
          gender?: string | null;
          phone: string;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          medical_history?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          age?: number | null;
          gender?: string | null;
          phone?: string;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          pincode?: string | null;
          medical_history?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      receipts: {
        Row: {
          id: string;
          user_id: string;
          client_id: string | null;
          receipt_number: string;
          receipt_type: 'physiotherapy' | 'pilates';
          receipt_status: 'draft' | 'issued' | 'cancelled' | 'modified';
          issue_date: string;
          client_name: string;
          client_age: number | null;
          client_phone: string;
          client_email: string | null;
          client_address: string | null;
          amount: number;
          payment_method: 'cash' | 'card' | 'upi' | 'bank_transfer' | 'other';
          description: string | null;
          diagnosis: string | null;
          treatment_details: string | null;
          session_count: number | null;
          membership_type: 'monthly' | 'quarterly' | 'annual' | null;
          membership_start_date: string | null;
          membership_end_date: string | null;
          tax_amount: number;
          total_amount: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          client_id?: string | null;
          receipt_number: string;
          receipt_type: 'physiotherapy' | 'pilates';
          receipt_status?: 'draft' | 'issued' | 'cancelled' | 'modified';
          issue_date: string;
          client_name: string;
          client_age?: number | null;
          client_phone: string;
          client_email?: string | null;
          client_address?: string | null;
          amount: number;
          payment_method: 'cash' | 'card' | 'upi' | 'bank_transfer' | 'other';
          description?: string | null;
          diagnosis?: string | null;
          treatment_details?: string | null;
          session_count?: number | null;
          membership_type?: 'monthly' | 'quarterly' | 'annual' | null;
          membership_start_date?: string | null;
          membership_end_date?: string | null;
          tax_amount?: number;
          total_amount: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          client_id?: string | null;
          receipt_number?: string;
          receipt_type?: 'physiotherapy' | 'pilates';
          receipt_status?: 'draft' | 'issued' | 'cancelled' | 'modified';
          issue_date?: string;
          client_name?: string;
          client_age?: number | null;
          client_phone?: string;
          client_email?: string | null;
          client_address?: string | null;
          amount?: number;
          payment_method?: 'cash' | 'card' | 'upi' | 'bank_transfer' | 'other';
          description?: string | null;
          diagnosis?: string | null;
          treatment_details?: string | null;
          session_count?: number | null;
          membership_type?: 'monthly' | 'quarterly' | 'annual' | null;
          membership_start_date?: string | null;
          membership_end_date?: string | null;
          tax_amount?: number;
          total_amount?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      receipt_changes: {
        Row: {
          id: string;
          receipt_id: string;
          changed_by: string | null;
          change_type: string;
          field_name: string | null;
          old_value: string | null;
          new_value: string | null;
          change_reason: string | null;
          changed_at: string;
        };
        Insert: {
          id?: string;
          receipt_id: string;
          changed_by?: string | null;
          change_type: string;
          field_name?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          change_reason?: string | null;
          changed_at?: string;
        };
        Update: {
          id?: string;
          receipt_id?: string;
          changed_by?: string | null;
          change_type?: string;
          field_name?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          change_reason?: string | null;
          changed_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          details: Record<string, any> | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          details?: Record<string, any> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          details?: Record<string, any> | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
  };
}